name: Bump version on merge

on:
  pull_request:
    types:
      - closed

jobs:
  bump-version:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Bump version
      run: |
        if git log -1 --pretty=%B | grep -q "feat:"; then
          poetry run bumpversion minor
        elif git log -1 --pretty=%B | grep -q "BREAKING CHANGE:"; then
          poetry run bumpversion major
        else
          poetry run bumpversion patch
        fi

    - name: Push changes
      run: |
        git push origin HEAD:main
        git push --tags
