name: Synchronize Documentation Requirements

on:
  push:
    branches:
      - main
    paths:
      - 'pyproject.toml'
  pull_request:
    branches:
      - main
    paths:
      - 'pyproject.toml'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-docs-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in GITHUB_TOKEN

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install tomlkit for Python TOML manipulation
        run: pip install tomlkit

      - name: Update docs/requirements.txt
        run: |
          python .github/scripts/update_requirements.py

      - name: Check if changes were made
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: github.event_name == 'push' && steps.check_changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in GITHUB_TOKEN
          commit-message: Update docs/requirements.txt
          title: '[Automated] Update documentation requirements'
          branch: update-docs-requirements
          base: main
          body: |
            This is an automated pull request to update the documentation requirements based on pyproject.toml.
          labels: |
            automated PR

      - name: Verify requirements are in sync (PR only)
        if: github.event_name == 'pull_request' && steps.check_changes.outputs.changed == 'true'
        run: |
          echo "::error::Documentation requirements are out of sync with pyproject.toml"
          echo "Please run 'python .github/scripts/update_requirements.py' locally and commit the changes"
          exit 1
